### ISSUE TITLE
Fix the naming of the classes, methods and variables

### ISSUE THREAD

**Issue by dingo-d** [WordPress/Dynamic-Properties-Utils#2]
Seeing how this should get implemented in the WordPress Core, maybe it should be a good idea to format this according to the WPCS (underscore as separated, no StudlyCaps, etc.)?

**Comment by jrfnl** [comment]
@dingo-d The intention is to publish this as a separate package for anyone in the PHP community to use. WP would use it as an external dependency. With that in mind, the coding standard for this package has _deliberately_ been set to PSR12.

**Comment by dingo-d** [comment]
Oh wasn't aware of that 👍🏼
